import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export const workspaceSourcePaths = {
	telemetryIndex: fileURLToPath(new URL("./packages/telemetry/src/index.ts", import.meta.url)),
	telemetryTesting: fileURLToPath(new URL("./packages/telemetry/src/testing/index.ts", import.meta.url)),
	mcpIndex: fileURLToPath(new URL("./packages/mcp/src/index.ts", import.meta.url)),
	mcpOAuth: fileURLToPath(new URL("./packages/mcp/src/oauth/index.ts", import.meta.url)),
	mcpTesting: fileURLToPath(new URL("./packages/mcp/src/testing/index.ts", import.meta.url)),
	aiIndex: fileURLToPath(new URL("./packages/ai/src/index.ts", import.meta.url)),
	aiCompat: fileURLToPath(new URL("./packages/ai/src/compat.ts", import.meta.url)),
	aiOAuth: fileURLToPath(new URL("./packages/ai/src/oauth.ts", import.meta.url)),
	aiProviders: fileURLToPath(new URL("./packages/ai/src/providers", import.meta.url)),
	aiSrc: fileURLToPath(new URL("./packages/ai/src", import.meta.url)),
	durableIndex: fileURLToPath(new URL("./packages/durable/src/index.ts", import.meta.url)),
	agentIndex: fileURLToPath(new URL("./packages/agent/src/index.ts", import.meta.url)),
	chordIndex: fileURLToPath(new URL("./packages/chord/src/index.ts", import.meta.url)),
	chordContext: fileURLToPath(new URL("./packages/chord/src/context/index.ts", import.meta.url)),
	chordDelta: fileURLToPath(new URL("./packages/chord/src/delta/index.ts", import.meta.url)),
	chordBundler: fileURLToPath(new URL("./packages/chord/src/bundler.ts", import.meta.url)),
	chordNode: fileURLToPath(new URL("./packages/chord/src/node.ts", import.meta.url)),
	codemodeIndex: fileURLToPath(new URL("./packages/codemode/src/index.ts", import.meta.url)),
	codemodeDeclarations: fileURLToPath(new URL("./packages/codemode/src/declarations.ts", import.meta.url)),
	codemodeSource: fileURLToPath(new URL("./packages/codemode/src/source.ts", import.meta.url)),
	codemodeWorker: fileURLToPath(new URL("./packages/codemode/src/runtime/worker.ts", import.meta.url)),
	protocolIndex: fileURLToPath(new URL("./packages/protocol/src/index.ts", import.meta.url)),
	clientIndex: fileURLToPath(new URL("./packages/client/src/index.ts", import.meta.url)),
	clientControl: fileURLToPath(new URL("./packages/client/src/control.ts", import.meta.url)),
	clientUnix: fileURLToPath(new URL("./packages/client/src/unix.ts", import.meta.url)),
	serverIndex: fileURLToPath(new URL("./packages/server/src/index.ts", import.meta.url)),
	serverUnix: fileURLToPath(new URL("./packages/server/src/transports/unix/index.ts", import.meta.url)),
	codingAgentIndex: fileURLToPath(new URL("./packages/cli/src/index.ts", import.meta.url)),
	tuiIndex: fileURLToPath(new URL("./packages/tui/src/index.ts", import.meta.url)),
} as const;

export default defineConfig({
	resolve: {
		alias: [
			{ find: /^@knightcode\/telemetry$/, replacement: workspaceSourcePaths.telemetryIndex },
			{ find: /^@knightcode\/telemetry\/testing$/, replacement: workspaceSourcePaths.telemetryTesting },
			{ find: /^@knightcode\/mcp$/, replacement: workspaceSourcePaths.mcpIndex },
			{ find: /^@knightcode\/mcp\/oauth$/, replacement: workspaceSourcePaths.mcpOAuth },
			{ find: /^@knightcode\/mcp\/testing$/, replacement: workspaceSourcePaths.mcpTesting },
			{ find: /^@knightcode\/ai$/, replacement: workspaceSourcePaths.aiIndex },
			{ find: /^@knightcode\/ai\/compat$/, replacement: workspaceSourcePaths.aiCompat },
			{ find: /^@knightcode\/ai\/oauth$/, replacement: workspaceSourcePaths.aiOAuth },
			{
				find: /^@knightcode\/ai\/providers\/(.+)$/,
				replacement: `${workspaceSourcePaths.aiProviders}/$1.ts`,
			},
			{
				find: /^@knightcode\/ai\/((?:utils|api|auth)\/.+)$/,
				replacement: `${workspaceSourcePaths.aiSrc}/$1.ts`,
			},
			{ find: /^@knightcode\/durable$/, replacement: workspaceSourcePaths.durableIndex },
			{
				find: /^@knightcode\/durable\/testing$/,
				replacement: fileURLToPath(new URL("./packages/durable/src/testing/index.ts", import.meta.url)),
			},
			{ find: /^@knightcode\/agent$/, replacement: workspaceSourcePaths.agentIndex },
			{
				find: /^@knightcode\/agent\/harness\/session$/,
				replacement: fileURLToPath(new URL("./packages/agent/src/harness/session/index.ts", import.meta.url)),
			},
			{
				find: /^@knightcode\/agent\/harness\/session\/testing$/,
				replacement: fileURLToPath(new URL("./packages/agent/src/harness/session/testing/index.ts", import.meta.url)),
			},
			{
				find: /^@knightcode\/agent\/experimental\/pico3$/,
				replacement: fileURLToPath(new URL("./packages/agent/src/harness/pico3/index.ts", import.meta.url)),
			},
			{ find: /^@knightcode\/chord$/, replacement: workspaceSourcePaths.chordIndex },
			{ find: /^@knightcode\/chord\/context$/, replacement: workspaceSourcePaths.chordContext },
			{ find: /^@knightcode\/chord\/delta$/, replacement: workspaceSourcePaths.chordDelta },
			{ find: /^@knightcode\/chord\/bundler$/, replacement: workspaceSourcePaths.chordBundler },
			{ find: /^@knightcode\/chord\/node$/, replacement: workspaceSourcePaths.chordNode },
			{ find: /^@knightcode\/codemode$/, replacement: workspaceSourcePaths.codemodeIndex },
			{ find: /^@knightcode\/codemode\/declarations$/, replacement: workspaceSourcePaths.codemodeDeclarations },
			{ find: /^@knightcode\/codemode\/source$/, replacement: workspaceSourcePaths.codemodeSource },
			{ find: /^@knightcode\/codemode\/worker$/, replacement: workspaceSourcePaths.codemodeWorker },
			{ find: /^@knightcode\/protocol$/, replacement: workspaceSourcePaths.protocolIndex },
			{ find: /^@knightcode\/client$/, replacement: workspaceSourcePaths.clientIndex },
			{ find: /^@knightcode\/client\/control$/, replacement: workspaceSourcePaths.clientControl },
			{ find: /^@knightcode\/client\/unix$/, replacement: workspaceSourcePaths.clientUnix },
			{ find: /^@knightcode\/server$/, replacement: workspaceSourcePaths.serverIndex },
			{ find: /^@knightcode\/server\/unix$/, replacement: workspaceSourcePaths.serverUnix },
			{ find: /^@knightcode\/tui$/, replacement: workspaceSourcePaths.tuiIndex },
		],
	},
});
