// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/agentrouter.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const AGENTROUTER_MODELS: ChatModelCatalog<typeof values, "agentrouter"> =
	flattenChatModelCatalog("agentrouter", values);

export const AGENTROUTER_IMAGE_MODELS: ImageModelCatalog<typeof values, "agentrouter"> =
	flattenImageModelCatalog("agentrouter", values);

export const AGENTROUTER_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "agentrouter"> =
	flattenClassifierModelCatalog("agentrouter", values);
